security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        # Configuración de un proveedor de usuarios en base de datos
        app_user_provider:
            entity:
                class: App\Entity\Usuarios  # Cambiado de User a Usuarios
                property: nombreUsuario  # Cambiado a nombreUsuario según tu entidad

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator  # Ajusta esto al autenticador que estés usando
            logout:
                path: app_logout
                target: home  # Redirección después de cerrar sesión

            # Punto de entrada si no estás autenticado
            entry_point: App\Security\LoginFormAuthenticator

    access_control:
        # Requiere autenticación para ciertas rutas
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/miembros, roles: ROLE_USER }
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
